
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/btsdb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 

  profiles:
    active: dev

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

#  ng serve --configuration=sit
